### PR TITLE
proper credit :D

### PR DESCRIPTION
**Pull request by TinyGamesCoding**

### CODE REVIEW

**Comment by TinyGamesCoding** [comment]
image
you cant make this stuff up

**Comment by TinyGamesCoding** [comment]
he apparently killed some source code 😭

**Comment by TinyGamesCoding** [comment]
ok, well i saved the source code with this fork

//i win

**Comment by imthosea** [comment]
> he apparently killed some source code 😭

pro tip: check over git logs before using `git push --force`

**Pull request closed without merging**
